# Generated by Django 5.0.6 on 2024-06-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                ("JobID", models.IntegerField(primary_key=True, serialize=False)),
                ("WindowID", models.IntegerField(null=True)),
                ("Title", models.CharField(max_length=255, null=True)),
                ("Description", models.TextField(null=True)),
                ("Requirements", models.TextField(null=True)),
                ("City", models.CharField(max_length=100, null=True)),
                ("State", models.CharField(max_length=100, null=True)),
                ("Country", models.CharField(max_length=100, null=True)),
                ("Zip5", models.FloatField(null=True)),
                ("StartDate", models.CharField(max_length=100, null=True)),
                ("EndDate", models.CharField(max_length=100, null=True)),
                ("job", models.CharField(max_length=100, null=True)),
                ("Combined", models.TextField(null=True)),
            ],
        ),
    ]
